// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemPeminjaman.Api.Models;

#nullable disable

namespace SistemPeminjaman.Api.Migrations
{
    [DbContext(typeof(SistemDbContext))]
    [Migration("20260211140434_InisialisasiAwal")]
    partial class InisialisasiAwal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("SistemPeminjaman.Api.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keperluan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tanggal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peminjamans");
                });

            modelBuilder.Entity("SistemPeminjaman.Api.Models.Ruangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapasitas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ruangans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kapasitas = 30,
                            Lokasi = "Gedung D3",
                            NamaRuangan = "Lab Informatika"
                        },
                        new
                        {
                            Id = 2,
                            Kapasitas = 200,
                            Lokasi = "Gedung Pusat",
                            NamaRuangan = "Aula Utama"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
